version: '3'

services:
  debauthn:
    # build: .
    image: "martinord/debauthn"
    ports:
      - "5000:5000"
    environment:
      - ORIGIN=https://debauthn.tic.udc.es
      - PORT=5000
      - SECRET="SecretForDeploymentPurposes!"
      - MONGO=mongo
      - TLS=false
      - RP_ID=localhost
      - RP_NAME=DebAuthn
  mongo:
    image: "mongo:5.0.5"
    ports:
      - "127.0.0.1:27017-27019:27017-27019"
